version: '3.8'

services:
  web:
    build:
      context: ./deployment/images
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - .:/var/www/html
      - ./deployment/config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./deployment/config/nginx/ssl.conf:/etc/nginx/conf.d/ssl.conf
      - ./deployment/config/nginx/ssl:/etc/nginx/ssl:ro
    working_dir: /var/www/html
    healthcheck:
      test: ["CMD-SHELL", "curl -f -k https://localhost:443/ || curl -f http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
